name: Publish

on: [push]

jobs:
  build:
    name: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [bash, csharp, haskell, java, java12, nodejs, prolog, python, r, scheme, scratch, security, c, tested]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: dodona/dodona-${{ matrix.image }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: dodona-${{ matrix.image }}.dockerfile
        snapshot: true
