name: Lint

on: [push]

jobs:
  lint:
    name: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [bash, csharp, haskell, java, java12, nodejs, prolog, python, r, scheme, security, c, tested]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: brpaz/hadolint-action@master
        with:
          dockerfile: dodona-${{ matrix.image }}.dockerfile
